language: node_js
node_js:
  - "0.11"
  - "0.10"

notifications:
hipchat:
  secure: "MftG2Vm1EUhj43QtT6CvXByKQqLZ4OC9lyOFTVf71qmQBcZtt0plfjt58Onte1gsMGQYZMX9Bja4QtmqKrE5qaa6cjgDRmHyUpCgjwP22Z2jY3WYUqGZg4sdkYR/bMfYlURPap7+Zbqxya8xB3NwT2KeNwrWb5iCdTAbG72NoNE="
